org.gradle.jvmargs=-Xmx2g
android.useAndroidX=true

GROUP=io.github.mataku
VERSION_NAME=0.2.0-SNAPSHOT
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/mataku/mitame
POM_SCM_URL=https://github.com/mataku/mitame
POM_SCM_CONNECTION=scm:git:git://github.com/mataku/mitame.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/mataku/mitame.git
POM_LICENSE_NAME=The MIT License (MIT)
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=mataku
POM_DEVELOPER_NAME=Takuma Homma
POM_DEVELOPER_URL=https://github.com/mataku/
mavenCentralPublishing=true
signAllPublications=true
