name: mitame_flutter_example
description: Example project for mitame_flutter.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mitame_flutter:
    path: ../

flutter:
  uses-material-design: true
